apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "envchart.labels" . }}
data:
{{- with .Values.configMap }}
  ENVIRONMENT: {{ .environment }}
  KEY_VAULT_ENDPOINT: {{ .keyVaultEndpoint }}
  APP_VERSION: {{ .appVersion | quote }}
  JAVA_OPTS: {{ .javaOpts }}
  MY_VALUE: {{ .myValue }}
{{- end }}  