---
apiVersion: v1
kind: ServiceAccount
metadata:
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "envchart.labels" . }}
  {{- with .Values.serviceAccount }}
  namespace: {{ .namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .annotations.clientId }}
  {{- end }} 